version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: localhub_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: localhub
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  postgres:
    image: postgis/postgis:16-3.4
    container_name: localhub_postgres
    restart: always
    volumes:
      - ./data/localhub-backend-db:/var/lib/postgresql/data

    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: localhub_postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
