server:
  port: 8082


#mysql:
#  datasource:
#    url: jdbc:mysql://localhost:3309/localhub
#    username: user
#    password: 1234
spring:
  datasource:
    url: ${MYSQL_DB_URL}
    username: ${MYSQL_DB_USERNAME}
    password: ${MYSQL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

#  postgis:
#    url: jdbc:postgresql://localhost:5433/localhub_geo
#    username: geo
#    password: 1234
#    driver-class-name: org.postgresql.Driver



  config:
    import: optional:file:.env[.properties]

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true



  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: never


  security:
    oauth2:
      client:
        registration:
          naver: # 서비스명
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_SECRET}
            redirect-uri: http://localhost:8082/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email


          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            redirect-uri: http://localhost:8082/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email


          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET}
            redirect-uri: http://localhost:8082/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
#              - name
#              - gender
#              - birthday
#              - birthyear
#              - phone_number
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: dgsaljklkdsagjldsajglajlk124asdf5125126tdsaaa
  expiration: 3600000


storage:
  provider: r2
  bucket: localhub
  accessKey: ${R2_ACCESS_KEY}
  secretKey: ${R2_SECRET_KEY}
  endpoint: ${R2_ENDPOINT}
  region: auto
  presignSecond: 300